hugo-dd-nginx:
    image: nutsllc/toybox-nginx:1.15.7-alpine
    container_name: hugo-dd-nginx
    volumes:
        - ../html:/usr/share/nginx/html
    environment:
        - TOYBOX_GID=${TOYBOX_GID}
        - TOYBOX_UID=${TOYBOX_UID}
        - VIRTUAL_HOST=${URL}
        - LETSENCRYPT_HOST=${URL}
        - LETSENCRYPT_EMAIL=${EMAIL}
    ports:
        - "80"
